l_english:
 PRODUCTION_MATERIALS_ALUMINIUM:0 "Aluminium"
 PRODUCTION_VEHICLES_BUTTON:0 "Build Armoured Vehicles"
 PRODUCTION_VEHICLES_BUTTON_DISABLED:0 "Armoured Vehicles are §RNot invented§!!"
 PRODUCTION_DEPLOY_TO_RESERVE_FLEET_THEATER:1 "Deploy to the Reserve of theatre: $THEATER|H$"
 PRODUCTION_NAVAL_DEPLOYMENT_THEATER:0 "Deploy target theatre $THEATER|H$ with base in $STATE|H$."
 PRODUCTION_CIVILIAN_FACTORIES_SENT_TO_OTHERS:0 "Given to other countries: $VAL|R$"
 CARRIER_AIR_WING_LIMIT_DESC:0 "Aeroplanes/Carrier capacity"
 PRODUCTION_ARMOR_FILTER:0 "Armoured Vehicles"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_TOTAL_SIMPLE:0 "§HLicence production§!: $VALUE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_TOTAL:0 "§HLicence production factory output§!\nTotal: $VALUE|+%$\nBreakdown:"
 LICENSED_EQUIPMENT_TECH_SPEED_REDUCTION:1 "§YLicence technology difference§!:\n Base: $BASE|+%$\n Modified total: $TOTAL|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_MODIFIER:1 "§YLicence modifier§!:\n Base: $BASE|+%$\n Modified total: $TOTAL|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_NOT_FACTION:0 "§YNot in faction with licenser§!: $VALUE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_NO_LICENSE:0 "§YNo active licence§!: $VALUE|+%$"
 LICENSED_EQUIPMENT_UPGRADE_XP_COST_MODIFIER:0 "Licenced Equipment: $VAL$"
 LICENSED_PURCHASE_CIC_COST:1 "§YThis licence costs§!: £civ_factory $AMOUNT|Y$"